use std::{env, fmt::Write as _, fs, path::PathBuf};

const SCHED_FAMILY: EventFamilySpec = EventFamilySpec {
    proto_path: "proto/ftrace_data/sched.proto",
    builders_file: "sched_table_builders.rs",
    builders_name: "SchedDirectTableBuilders",
};

struct EventFamilySpec {
    proto_path: &'static str,
    builders_file: &'static str,
    builders_name: &'static str,
}

fn main() {
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc is available");
    let proto_files = ["proto/hitrace.proto", SCHED_FAMILY.proto_path];
    let sched_source = fs::read_to_string(SCHED_FAMILY.proto_path).expect("sched proto is read");
    let sched_messages = parse_proto_messages(&sched_source);
    let mut config = prost_build::Config::new();
    config.protoc_executable(protoc);
    config.type_attribute(
        ".kat.hitrace.ProfilerPluginData",
        "#[derive(serde::Serialize, serde::Deserialize)]",
    );
    for message in &sched_messages {
        let path = format!(".kat.hitrace.{}", message.name);
        config.type_attribute(&path, "#[derive(serde::Serialize, serde::Deserialize)]");
    }
    config.field_attribute(
        ".kat.hitrace.ProfilerPluginData.data",
        "#[serde(with = \"serde_bytes\")]",
    );
    config
        .compile_protos(&proto_files, &["proto"])
        .expect("hitrace and sched protos compile");
    generate_event_family_code(&SCHED_FAMILY, &sched_messages)
        .expect("event family generated code is written");

    for proto_file in proto_files {
        println!("cargo:rerun-if-changed={proto_file}");
    }
}

#[derive(Clone, Debug)]
struct ProtoMessage {
    name: String,
    table_name: String,
}

fn generate_event_family_code(
    family: &EventFamilySpec,
    messages: &[ProtoMessage],
) -> std::io::Result<()> {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    fs::write(
        out_dir.join(family.builders_file),
        render_event_table_builders(family, messages),
    )
}

fn parse_proto_messages(source: &str) -> Vec<ProtoMessage> {
    let mut messages = Vec::new();
    let mut current: Option<ProtoMessage> = None;

    for raw_line in source.lines() {
        let line = raw_line.trim();
        if line.starts_with("message ") && line.ends_with('{') {
            let name = line
                .trim_start_matches("message ")
                .trim_end_matches('{')
                .trim()
                .to_string();
            let base_name = name.strip_suffix("Format").unwrap_or(&name).to_string();
            current = Some(ProtoMessage {
                name,
                table_name: camel_to_snake(&base_name),
            });
            continue;
        }

        if line == "}" {
            if let Some(message) = current.take() {
                messages.push(message);
            }
            continue;
        }
    }

    messages
}

fn render_event_table_builders(family: &EventFamilySpec, messages: &[ProtoMessage]) -> String {
    let mut output = String::new();
    output.push_str("// @generated by crates/kat-rs-datasource/build.rs. Do not edit.\n\n");
    output.push_str("use anyhow::Result;\n\n");
    output.push_str("use crate::{\n");
    output.push_str("    hitrace::{EventMeta, EventRow, HitraceTable, TableBuilder},\n");
    output.push_str("    proto::kat::hitrace::{\n");
    output.push_str("        FtraceEvent,\n");
    for message in messages {
        writeln!(output, "        {},", message.name).expect("write to string");
    }
    output.push_str("    },\n");
    output.push_str("};\n\n");

    writeln!(output, "pub(crate) struct {} {{", family.builders_name).expect("write to string");
    for message in messages {
        writeln!(
            output,
            "    {}: TableBuilder<EventRow<{}>>,",
            message.table_name, message.name
        )
        .expect("write to string");
    }
    output.push_str("}\n\n");

    writeln!(output, "impl {} {{", family.builders_name).expect("write to string");
    output.push_str("    pub(crate) fn new() -> Result<Self> {\n");
    output.push_str("        Ok(Self {\n");
    for message in messages {
        writeln!(
            output,
            "            {}: TableBuilder::new_from_sample({:?})?,",
            message.table_name, message.table_name
        )
        .expect("write to string");
    }
    output.push_str("        })\n");
    output.push_str("    }\n\n");

    output.push_str(
        "    pub(crate) fn push_event(&mut self, cpu: u32, event: FtraceEvent) -> Result<()> {\n",
    );
    output.push_str("        let meta = EventMeta::from_event(cpu, &event);\n");
    for message in messages {
        writeln!(
            output,
            "        if let Some(message) = event.{} {{",
            event_field_name(message)
        )
        .expect("write to string");
        writeln!(
            output,
            "            self.{}.push(EventRow::new(meta.clone(), message))?;",
            message.table_name
        )
        .expect("write to string");
        output.push_str("        }\n");
    }
    output.push_str("\n        Ok(())\n");
    output.push_str("    }\n\n");

    output.push_str("    pub(crate) fn into_tables(self) -> Result<Vec<HitraceTable>> {\n");
    output.push_str("        Ok(vec![\n");
    for message in messages {
        writeln!(
            output,
            "            self.{}.into_table()?,",
            message.table_name
        )
        .expect("write to string");
    }
    output.push_str("        ])\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn event_field_name(message: &ProtoMessage) -> String {
    camel_to_snake(&message.name)
}

fn camel_to_snake(name: &str) -> String {
    let mut snake = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index != 0 {
                snake.push('_');
            }
            snake.push(ch.to_ascii_lowercase());
        } else {
            snake.push(ch);
        }
    }
    snake
}
