use std::{env, fmt::Write as _, fs, path::PathBuf};

const SCHED_PROTO: &str = "proto/ftrace_data/sched.proto";

fn main() {
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc is available");
    let proto_files = ["proto/hitrace.proto", SCHED_PROTO];
    let mut config = prost_build::Config::new();
    config.protoc_executable(protoc);
    config.type_attribute(
        ".kat.hitrace.ProfilerPluginData",
        "#[derive(serde::Serialize, serde::Deserialize)]",
    );
    config.type_attribute(
        ".SchedSwitchFormat",
        "#[derive(serde::Serialize, serde::Deserialize)]",
    );
    config.field_attribute(
        ".kat.hitrace.ProfilerPluginData.data",
        "#[serde(with = \"serde_bytes\")]",
    );
    config
        .compile_protos(&proto_files, &["proto"])
        .expect("hitrace and sched protos compile");
    generate_sched_code().expect("sched generated code is written");

    for proto_file in proto_files {
        println!("cargo:rerun-if-changed={proto_file}");
    }
}

#[derive(Clone, Debug)]
struct ProtoMessage {
    name: String,
    row_name: String,
    table_name: String,
    fields: Vec<ProtoField>,
}

#[derive(Clone, Debug)]
struct ProtoField {
    rust_type: &'static str,
    name: String,
}

fn generate_sched_code() -> std::io::Result<()> {
    let source = fs::read_to_string(SCHED_PROTO)?;
    let messages = parse_proto_messages(&source);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    fs::write(out_dir.join("sched_rows.rs"), render_sched_rows(&messages))?;
    fs::write(
        out_dir.join("sched_table_builders.rs"),
        render_sched_table_builders(&messages),
    )
}

fn parse_proto_messages(source: &str) -> Vec<ProtoMessage> {
    let mut messages = Vec::new();
    let mut current: Option<ProtoMessage> = None;

    for raw_line in source.lines() {
        let line = raw_line.trim();
        if line.starts_with("message ") && line.ends_with('{') {
            let name = line
                .trim_start_matches("message ")
                .trim_end_matches('{')
                .trim()
                .to_string();
            let base_name = name.strip_suffix("Format").unwrap_or(&name).to_string();
            current = Some(ProtoMessage {
                name,
                row_name: format!("{base_name}Row"),
                table_name: camel_to_snake(&base_name),
                fields: Vec::new(),
            });
            continue;
        }

        if line == "}" {
            if let Some(message) = current.take() {
                messages.push(message);
            }
            continue;
        }

        let Some(message) = current.as_mut() else {
            continue;
        };
        let field_line = line
            .split_once("//")
            .map_or(line, |(field, _comment)| field)
            .trim()
            .trim_end_matches(';');
        let parts: Vec<_> = field_line.split_whitespace().collect();
        if parts.len() < 4 || parts[2] != "=" {
            continue;
        }

        message.fields.push(ProtoField {
            rust_type: rust_type(parts[0]),
            name: parts[1].to_string(),
        });
    }

    messages
}

fn render_sched_rows(messages: &[ProtoMessage]) -> String {
    let mut output = String::new();
    output.push_str("// @generated by crates/kat-rs-datasource/build.rs. Do not edit.\n\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");
    output.push_str("use crate::proto::{\n");
    output.push_str("    kat::hitrace::FtraceEvent,\n");
    for message in messages {
        writeln!(output, "    {},", message.name).expect("write to string");
    }
    output.push_str("};\n\n");

    output.push_str("#[allow(dead_code)]\n");
    output.push_str("#[derive(Clone, Debug)]\n");
    output.push_str("pub(crate) struct SchedEventMeta {\n");
    output.push_str("    pub(crate) event_timestamp: u64,\n");
    output.push_str("    pub(crate) event_cpu: u32,\n");
    output.push_str("    pub(crate) event_tgid: i32,\n");
    output.push_str("    pub(crate) event_comm: String,\n");
    output.push_str("}\n\n");
    output.push_str("#[allow(dead_code)]\n");
    output.push_str("impl SchedEventMeta {\n");
    output.push_str("    pub(crate) fn from_event(cpu: u32, event: &FtraceEvent) -> Self {\n");
    output.push_str("        Self {\n");
    output.push_str("            event_timestamp: event.timestamp,\n");
    output.push_str("            event_cpu: cpu,\n");
    output.push_str("            event_tgid: event.tgid,\n");
    output.push_str("            event_comm: event.comm.clone(),\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    for message in messages {
        render_row_struct(&mut output, message);
    }

    output
}

fn render_sched_table_builders(messages: &[ProtoMessage]) -> String {
    let mut output = String::new();
    output.push_str("// @generated by crates/kat-rs-datasource/build.rs. Do not edit.\n\n");
    output.push_str("use anyhow::Result;\n\n");
    output.push_str("use crate::{\n");
    output.push_str("    hitrace::{HitraceTable, TableBuilder},\n");
    output.push_str("    proto::kat::hitrace::FtraceEvent,\n");
    output.push_str("    sched_rows::{\n");
    output.push_str("        SchedEventMeta,\n");
    for message in messages {
        writeln!(output, "        {},", message.row_name).expect("write to string");
    }
    output.push_str("    },\n");
    output.push_str("};\n\n");

    output.push_str("pub(crate) trait SchedEventObserver {\n");
    for message in messages {
        writeln!(
            output,
            "    fn observe_{}(&mut self, _row: &{}) {{}}",
            message.table_name, message.row_name
        )
        .expect("write to string");
    }
    output.push_str("}\n\n");

    output.push_str("pub(crate) struct SchedDirectTableBuilders {\n");
    for message in messages {
        writeln!(
            output,
            "    {}: TableBuilder<{}>,",
            message.table_name, message.row_name
        )
        .expect("write to string");
    }
    output.push_str("}\n\n");

    output.push_str("impl SchedDirectTableBuilders {\n");
    output.push_str("    pub(crate) fn new() -> Result<Self> {\n");
    output.push_str("        Ok(Self {\n");
    for message in messages {
        writeln!(
            output,
            "            {}: TableBuilder::new({}::TABLE_NAME)?,",
            message.table_name, message.row_name
        )
        .expect("write to string");
    }
    output.push_str("        })\n");
    output.push_str("    }\n\n");

    output.push_str(
        "    pub(crate) fn push_event<O>(&mut self, cpu: u32, event: FtraceEvent, observer: &mut O) -> Result<()>\n",
    );
    output.push_str("    where\n");
    output.push_str("        O: SchedEventObserver,\n");
    output.push_str("    {\n");
    output.push_str("        let meta = SchedEventMeta::from_event(cpu, &event);\n\n");
    for message in messages {
        writeln!(
            output,
            "        if let Some(message) = event.{} {{",
            event_field_name(message)
        )
        .expect("write to string");
        writeln!(
            output,
            "            let row = {}::new(&meta, message);",
            message.row_name
        )
        .expect("write to string");
        writeln!(
            output,
            "            observer.observe_{}(&row);",
            message.table_name
        )
        .expect("write to string");
        writeln!(
            output,
            "            self.{}.push(row)?;",
            message.table_name
        )
        .expect("write to string");
        output.push_str("        }\n");
    }
    output.push_str("\n        Ok(())\n");
    output.push_str("    }\n\n");

    output.push_str("    pub(crate) fn into_tables(self) -> Result<Vec<HitraceTable>> {\n");
    output.push_str("        Ok(vec![\n");
    for message in messages {
        writeln!(
            output,
            "            self.{}.into_table()?,",
            message.table_name
        )
        .expect("write to string");
    }
    output.push_str("        ])\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn render_row_struct(output: &mut String, message: &ProtoMessage) {
    writeln!(output, "#[allow(dead_code)]").expect("write to string");
    writeln!(output, "#[derive(Clone, Debug, Serialize, Deserialize)]").expect("write to string");
    writeln!(output, "pub(crate) struct {} {{", message.row_name).expect("write to string");
    output.push_str("    pub(crate) event_timestamp: u64,\n");
    output.push_str("    pub(crate) event_cpu: u32,\n");
    output.push_str("    pub(crate) event_tgid: i32,\n");
    output.push_str("    pub(crate) event_comm: String,\n");
    for field in &message.fields {
        writeln!(
            output,
            "    pub(crate) {}: {},",
            field.name, field.rust_type
        )
        .expect("write to string");
    }
    output.push_str("}\n\n");

    writeln!(output, "#[allow(dead_code)]").expect("write to string");
    writeln!(output, "impl {} {{", message.row_name).expect("write to string");
    writeln!(
        output,
        "    pub(crate) const TABLE_NAME: &'static str = {:?};",
        message.table_name
    )
    .expect("write to string");
    writeln!(
        output,
        "    pub(crate) fn new(meta: &SchedEventMeta, message: {}) -> Self {{",
        message.name
    )
    .expect("write to string");
    output.push_str("        Self {\n");
    output.push_str("            event_timestamp: meta.event_timestamp,\n");
    output.push_str("            event_cpu: meta.event_cpu,\n");
    output.push_str("            event_tgid: meta.event_tgid,\n");
    output.push_str("            event_comm: meta.event_comm.clone(),\n");
    for field in &message.fields {
        writeln!(
            output,
            "            {}: message.{},",
            field.name, field.name
        )
        .expect("write to string");
    }
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn rust_type(proto_type: &str) -> &'static str {
    match proto_type {
        "string" => "String",
        "int32" => "i32",
        "int64" => "i64",
        "uint32" => "u32",
        "uint64" => "u64",
        "bool" => "bool",
        "double" => "f64",
        "float" => "f32",
        "bytes" => "Vec<u8>",
        _ => panic!("unsupported sched proto field type {proto_type}"),
    }
}

fn event_field_name(message: &ProtoMessage) -> String {
    camel_to_snake(&message.name)
}

fn camel_to_snake(name: &str) -> String {
    let mut snake = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index != 0 {
                snake.push('_');
            }
            snake.push(ch.to_ascii_lowercase());
        } else {
            snake.push(ch);
        }
    }
    snake
}
