[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kat-workflow"
version = "0.1.1-rc.10"
requires-python = ">=3.14,<3.15"
dependencies = [
    "kat-sdk==0.1.0",
    "adbc-driver-manager==1.11.0",
    "adbc-driver-postgresql==1.11.0",
    "click==8.4.2",
    "pytest==9.1.1",
]

[tool.setuptools]
include-package-data = false
packages = ["_kat_runtime"]
package-dir = { "_kat_runtime" = "runtime" }
