[package]
name = "kat-datasource"
edition.workspace = true
version.workspace = true
publish.workspace = true

[features]
python-extension = ["dep:pyo3"]

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
log.workspace = true
memmap2.workspace = true
parquet.workspace = true
prost.workspace = true
pyo3 = { workspace = true, optional = true }
serde.workspace = true
serde_arrow.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[target.'cfg(any(target_os = "android", target_os = "linux", target_os = "redox", target_vendor = "apple"))'.dependencies]
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[build-dependencies]
heck.workspace = true
prost-build.workspace = true
prost-reflect.workspace = true
prost-types.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
heck.workspace = true
prost-build.workspace = true
prost-reflect.workspace = true
prost-types.workspace = true
protoc-bin-vendored.workspace = true
