//! 根据 htrace.proto descriptor 生成 htrace 表/列映射代码。

use heck::ToSnakeCase;
use prost_reflect::{FieldDescriptor, Kind, MessageDescriptor};
use std::fmt::Write as _;
use std::path::PathBuf;

/// 读取 htrace descriptor，并生成表/列映射实例。
fn main() {
    println!("cargo:rerun-if-changed=../trace-proto/proto/htrace.proto");

    let pool = prost_reflect::DescriptorPool::decode(trace_proto::FILE_DESCRIPTOR_SET)
        .expect("htrace descriptor set decodes");
    let root = pool
        .get_message_by_name("kat.htrace.HtraceTrace")
        .expect("kat.htrace.HtraceTrace exists");
    let tables = collect_tables(&root);
    let code = render_table_specs(&tables);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set"));
    std::fs::write(out_dir.join("htrace_table_specs_generated.rs"), code)
        .expect("generated htrace table specs are written");
}

/// 构建期表结构。
struct GeneratedTable {
    const_name: String,
    name: String,
    source: String,
    repeated_field: String,
    fields: Vec<GeneratedField>,
}

/// 构建期字段结构。
struct GeneratedField {
    name: String,
    source: String,
    arrow_type: &'static str,
    nullable: bool,
    repeated: bool,
}

/// 从根 message 的 repeated message 字段收集基础表。
fn collect_tables(root: &MessageDescriptor) -> Vec<GeneratedTable> {
    root.fields()
        .filter_map(|field| {
            if !field.is_list() {
                return None;
            }
            let Kind::Message(message) = field.kind() else {
                return None;
            };
            Some(GeneratedTable {
                const_name: format!("{}_FIELDS", message.name().to_snake_case().to_uppercase()),
                name: message.name().to_snake_case(),
                source: message.full_name().to_string(),
                repeated_field: field.name().to_string(),
                fields: collect_fields(&message),
            })
        })
        .collect()
}

/// 收集一个输出 message 的可导出字段。
fn collect_fields(message: &MessageDescriptor) -> Vec<GeneratedField> {
    message
        .fields()
        .map(|field| GeneratedField {
            name: field.name().to_snake_case(),
            source: field.name().to_string(),
            arrow_type: arrow_type_for_field(&field),
            nullable: field.field_descriptor_proto().proto3_optional(),
            repeated: field.is_list(),
        })
        .collect()
}

/// 将 protobuf 字段类型映射到 trace_arrow::ArrowType variant。
fn arrow_type_for_field(field: &FieldDescriptor) -> &'static str {
    match field.kind() {
        Kind::Bool => "Boolean",
        Kind::Int32 | Kind::Sint32 | Kind::Sfixed32 | Kind::Enum(_) => "Int32",
        Kind::Uint32 | Kind::Fixed32 => "UInt32",
        Kind::Int64 | Kind::Sint64 | Kind::Sfixed64 => "Int64",
        Kind::Uint64 | Kind::Fixed64 => "UInt64",
        Kind::Float => "Float32",
        Kind::Double => "Float64",
        Kind::String => "Utf8",
        Kind::Bytes => "Binary",
        Kind::Message(_) => {
            panic!(
                "nested protobuf message field is not supported: {}",
                field.full_name()
            )
        }
    }
}

/// 渲染 Rust 表/列映射常量。
fn render_table_specs(tables: &[GeneratedTable]) -> String {
    let mut code = String::new();
    code.push_str("// @generated by trace-htrace/build.rs\n");
    code.push('\n');

    for table in tables {
        writeln!(
            code,
            "const {}: &[trace_arrow::FieldSpec] = &[",
            table.const_name
        )
        .expect("write field const");
        for field in &table.fields {
            writeln!(
                code,
                "    trace_arrow::FieldSpec {{ name: \"{}\", source: \"{}\", arrow_type: trace_arrow::ArrowType::{}, nullable: {}, repeated: {} }},",
                field.name, field.source, field.arrow_type, field.nullable, field.repeated
            )
            .expect("write field spec");
        }
        code.push_str("];\n\n");
    }

    code.push_str("const TABLE_SPECS: &[trace_arrow::TableSpec] = &[\n");
    for table in tables {
        writeln!(
            code,
            "    trace_arrow::TableSpec {{ name: \"{}\", source: \"{}\", repeated_field: \"{}\", fields: {} }},",
            table.name, table.source, table.repeated_field, table.const_name
        )
        .expect("write table spec");
    }
    code.push_str("];\n\n");
    code.push_str("pub fn table_specs() -> &'static [trace_arrow::TableSpec] {\n");
    code.push_str("    TABLE_SPECS\n");
    code.push_str("}\n");

    code
}
