[package]
name = "trace-htrace"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
htrace-proto = { path = "../htrace-proto" }
prost.workspace = true
prost-reflect.workspace = true
trace-arrow = { path = "../trace-arrow" }

[build-dependencies]
heck.workspace = true
htrace-proto = { path = "../htrace-proto" }
prost-reflect.workspace = true

[dev-dependencies]
prost.workspace = true
