syntax = "proto3";

package ftrace2parquet;

message TextFtraceEvent {
  string clock_domain = 1;
  uint64 clock_value = 2;
  uint32 cpu = 3;
  string emitter_thread_name = 4;
  int32 emitter_thread_id = 5;
  optional int32 emitter_process_id = 6;
  string context_flags = 7;

  oneof payload {
    SchedSwitch sched_switch = 8;
    SchedWakeup sched_wakeup = 9;
    SchedWakeupNew sched_wakeup_new = 10;
    TracingMarkWrite tracing_mark_write = 11;
    SchedBlockedReason sched_blocked_reason = 12;
    FilemapPageCache mm_filemap_add_to_page_cache = 13;
    FilemapPageCache mm_filemap_delete_from_page_cache = 14;
    BlockRqIssue block_rq_issue = 15;
    BlockRqComplete block_rq_complete = 16;
    BinderTransaction binder_transaction = 17;
    Print print = 18;
  }
}

message SchedSwitch {
  string previous_thread_name = 1;
  int32 previous_thread_id = 2;
  int32 previous_priority = 3;
  string previous_state = 4;
  string next_thread_name = 5;
  int32 next_thread_id = 6;
  int32 next_priority = 7;
}

message SchedWakeup {
  string thread_name = 1;
  int32 thread_id = 2;
  int32 priority = 3;
  uint32 target_cpu = 4;
}

message SchedWakeupNew {
  string thread_name = 1;
  int32 thread_id = 2;
  int32 priority = 3;
  uint32 target_cpu = 4;
}

message TracingMarkWrite {
  string content = 1;
}

message SchedBlockedReason {
  int32 pid = 1;
  uint32 io_wait = 2;
  string caller = 3;
}

message FilemapPageCache {
  uint32 device_major = 1;
  uint32 device_minor = 2;
  uint64 inode = 3;
  uint64 page_frame_number = 4;
  uint64 offset_bytes = 5;
  optional uint32 order = 6;
  optional string page_address = 7;
}

message BlockRqIssue {
  uint32 device_major = 1;
  uint32 device_minor = 2;
  string rwbs = 3;
  uint32 bytes = 4;
  string command = 5;
  uint64 sector = 6;
  uint32 sector_count = 7;
  string process_name = 8;
}

message BlockRqComplete {
  uint32 device_major = 1;
  uint32 device_minor = 2;
  string rwbs = 3;
  string command = 4;
  uint64 sector = 5;
  uint32 sector_count = 6;
  int32 error = 7;
}

message BinderTransaction {
  int32 transaction_id = 1;
  int32 destination_node_id = 2;
  int32 destination_process_id = 3;
  int32 destination_thread_id = 4;
  int32 reply = 5;
  uint32 flags = 6;
  uint32 code = 7;
}

message Print {
  string instruction_pointer = 1;
  string content = 2;
}
